version: '3.8'

networks:
  services:
    name: cluster

services:
  price-validation-mock:
    container_name: price-validation-mock
    build:
      context: ./price-validation-mock
    networks:
      - services
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/__admin/requests || exit 1" ]
      start_period: 10s  # increased to allow the container to initialize properly
      interval: 5s       # interval between health checks
      timeout: 2s        # timeout for each health check
      retries: 3         # number of retries before considering the service unhealthy
    ports:
      - "8081:8080"